apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-deployment.yaml
  - gateway-svc.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: gateway
    path: prod_patches/gateway-prod.yaml