apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-deployment.yaml
  - gateway-svc.yaml
  
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: gateway-svc
    path: local_patches/gateway-svc-dev.yaml